name: CI

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tidy:
    uses: taiki-e/github-actions/.github/workflows/tidy.yml@3637cc7cf76d2ce698edc313bcd39bad8a92caa8 # main
    permissions:
      security-events: write # for github/codeql-action/*
  miri:
    needs: tidy
    uses: taiki-e/github-actions/.github/workflows/rust-miri.yml@3637cc7cf76d2ce698edc313bcd39bad8a92caa8 # main
  msrv:
    needs: tidy
    uses: taiki-e/github-actions/.github/workflows/rust-msrv.yml@3637cc7cf76d2ce698edc313bcd39bad8a92caa8 # main
  test:
    needs: tidy
    uses: taiki-e/github-actions/.github/workflows/rust-test.yml@3637cc7cf76d2ce698edc313bcd39bad8a92caa8 # main
    with:
      doctest-nightly-only: true
      build-args: --depth 2 --features unstable
